let arr = [1,2,3,4,5,6];
arr.push(7,8,9);
console.log(arr);
let rel=arr.pop();
console.log(rel);
console.log(arr);
arr.unshift(0);
console.log(arr);
arr.shift();
console.log(arr);
arr.splice(1,3,8,9,11);
console.log(arr);